version: "3.8"

services: 
  server:
    # image: 'nginx:stable-alpine' 
    build:
      context: . # set context to root to be able to reach src and nginx folders
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/config.d/default.conf:ro # /etc/nginx/config.d/default.conf: is a special file which will be merge on a biiger nginx config inside nginx image
    depends_on:
      - php
      - mysql

  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    #volumes: # Uncomment this on development to reflect local changes to container
    #  - ./src:/var/www/html:delegated # delegated - means it's not copy immediately
      
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan'] # reuse php service then add entrypoint instruction  

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
